imports:
    - { resource: factory.php }
parameters:
    database_driver: pdo_pgsql
    database_host: %DB_HOST%
    database_port: %DB_PORT%
    database_name: %DB_NAME%
    database_user: %DB_USER%
    database_password: %DB_PASSWORD%
    mailer_transport: ~
    mailer_encryption: ~
    mailer_auth_mode: ~
    mailer_host: ~
    mailer_user: ~
    mailer_password: ~
    locale: ru
    secret: secret_code
    memcache_host: %CACHE_HOST%
    memcache_port: %CACHE_PORT%

    # Sonata Admin Options
    sonata_admin.title:             Sonata Project
    sonata_admin.logo_title:        /bundles/sonataadmin/logo_title.png

    # Sonata News Options
    sonata_news.blog_title:         My Awesome Blog
    sonata_news.blog_link:          http://awesome-blog.ltd
    sonata_news.blog_description:   My Awesome blog description
    sonata_news.salt:               ThisTokenIsNotSoSecretChangeIt
    sonata_news.comment.emails:     [mail@example.org]
    sonata_news.comment.email_from: no-reply@example.org

    # Sonata Media options
    sonata_media.cdn.host:          /data/uploads/media
